/**
 * generated by Xtext 2.14.0
 */
package com.ufcg.compiler.go;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>COMPARISON</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.ufcg.compiler.go.COMPARISON#getIgual <em>Igual</em>}</li>
 *   <li>{@link com.ufcg.compiler.go.COMPARISON#getMaiorigualque <em>Maiorigualque</em>}</li>
 *   <li>{@link com.ufcg.compiler.go.COMPARISON#getMenorigualque <em>Menorigualque</em>}</li>
 *   <li>{@link com.ufcg.compiler.go.COMPARISON#getMaiorque <em>Maiorque</em>}</li>
 *   <li>{@link com.ufcg.compiler.go.COMPARISON#getMenorque <em>Menorque</em>}</li>
 * </ul>
 *
 * @see com.ufcg.compiler.go.GoPackage#getCOMPARISON()
 * @model
 * @generated
 */
public interface COMPARISON extends EObject
{
  /**
   * Returns the value of the '<em><b>Igual</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Igual</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Igual</em>' attribute.
   * @see #setIgual(String)
   * @see com.ufcg.compiler.go.GoPackage#getCOMPARISON_Igual()
   * @model
   * @generated
   */
  String getIgual();

  /**
   * Sets the value of the '{@link com.ufcg.compiler.go.COMPARISON#getIgual <em>Igual</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Igual</em>' attribute.
   * @see #getIgual()
   * @generated
   */
  void setIgual(String value);

  /**
   * Returns the value of the '<em><b>Maiorigualque</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Maiorigualque</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Maiorigualque</em>' attribute.
   * @see #setMaiorigualque(String)
   * @see com.ufcg.compiler.go.GoPackage#getCOMPARISON_Maiorigualque()
   * @model
   * @generated
   */
  String getMaiorigualque();

  /**
   * Sets the value of the '{@link com.ufcg.compiler.go.COMPARISON#getMaiorigualque <em>Maiorigualque</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Maiorigualque</em>' attribute.
   * @see #getMaiorigualque()
   * @generated
   */
  void setMaiorigualque(String value);

  /**
   * Returns the value of the '<em><b>Menorigualque</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Menorigualque</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Menorigualque</em>' attribute.
   * @see #setMenorigualque(String)
   * @see com.ufcg.compiler.go.GoPackage#getCOMPARISON_Menorigualque()
   * @model
   * @generated
   */
  String getMenorigualque();

  /**
   * Sets the value of the '{@link com.ufcg.compiler.go.COMPARISON#getMenorigualque <em>Menorigualque</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Menorigualque</em>' attribute.
   * @see #getMenorigualque()
   * @generated
   */
  void setMenorigualque(String value);

  /**
   * Returns the value of the '<em><b>Maiorque</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Maiorque</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Maiorque</em>' attribute.
   * @see #setMaiorque(String)
   * @see com.ufcg.compiler.go.GoPackage#getCOMPARISON_Maiorque()
   * @model
   * @generated
   */
  String getMaiorque();

  /**
   * Sets the value of the '{@link com.ufcg.compiler.go.COMPARISON#getMaiorque <em>Maiorque</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Maiorque</em>' attribute.
   * @see #getMaiorque()
   * @generated
   */
  void setMaiorque(String value);

  /**
   * Returns the value of the '<em><b>Menorque</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Menorque</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Menorque</em>' attribute.
   * @see #setMenorque(String)
   * @see com.ufcg.compiler.go.GoPackage#getCOMPARISON_Menorque()
   * @model
   * @generated
   */
  String getMenorque();

  /**
   * Sets the value of the '{@link com.ufcg.compiler.go.COMPARISON#getMenorque <em>Menorque</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Menorque</em>' attribute.
   * @see #getMenorque()
   * @generated
   */
  void setMenorque(String value);

} // COMPARISON
