/**
 * generated by Xtext 2.14.0
 */
package com.ufcg.compiler.go;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Decl</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.ufcg.compiler.go.GoDecl#getVar <em>Var</em>}</li>
 *   <li>{@link com.ufcg.compiler.go.GoDecl#getFunc <em>Func</em>}</li>
 * </ul>
 *
 * @see com.ufcg.compiler.go.GoPackage#getGoDecl()
 * @model
 * @generated
 */
public interface GoDecl extends EObject
{
  /**
   * Returns the value of the '<em><b>Var</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Var</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Var</em>' containment reference.
   * @see #setVar(VarDecl)
   * @see com.ufcg.compiler.go.GoPackage#getGoDecl_Var()
   * @model containment="true"
   * @generated
   */
  VarDecl getVar();

  /**
   * Sets the value of the '{@link com.ufcg.compiler.go.GoDecl#getVar <em>Var</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Var</em>' containment reference.
   * @see #getVar()
   * @generated
   */
  void setVar(VarDecl value);

  /**
   * Returns the value of the '<em><b>Func</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Func</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Func</em>' containment reference.
   * @see #setFunc(FUNCAO)
   * @see com.ufcg.compiler.go.GoPackage#getGoDecl_Func()
   * @model containment="true"
   * @generated
   */
  FUNCAO getFunc();

  /**
   * Sets the value of the '{@link com.ufcg.compiler.go.GoDecl#getFunc <em>Func</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Func</em>' containment reference.
   * @see #getFunc()
   * @generated
   */
  void setFunc(FUNCAO value);

} // GoDecl
