/**
 * generated by Xtext 2.14.0
 */
package com.ufcg.compiler.go;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see com.ufcg.compiler.go.GoFactory
 * @model kind="package"
 * @generated
 */
public interface GoPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "go";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.ufcg.com/compiler/Go";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "go";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  GoPackage eINSTANCE = com.ufcg.compiler.go.impl.GoPackageImpl.init();

  /**
   * The meta object id for the '{@link com.ufcg.compiler.go.impl.InitImpl <em>Init</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.ufcg.compiler.go.impl.InitImpl
   * @see com.ufcg.compiler.go.impl.GoPackageImpl#getInit()
   * @generated
   */
  int INIT = 0;

  /**
   * The feature id for the '<em><b>Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INIT__ELEMENTS = 0;

  /**
   * The number of structural features of the '<em>Init</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INIT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link com.ufcg.compiler.go.impl.GoDeclImpl <em>Decl</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.ufcg.compiler.go.impl.GoDeclImpl
   * @see com.ufcg.compiler.go.impl.GoPackageImpl#getGoDecl()
   * @generated
   */
  int GO_DECL = 1;

  /**
   * The feature id for the '<em><b>Var</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GO_DECL__VAR = 0;

  /**
   * The feature id for the '<em><b>Func</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GO_DECL__FUNC = 1;

  /**
   * The number of structural features of the '<em>Decl</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GO_DECL_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link com.ufcg.compiler.go.impl.VarDeclImpl <em>Var Decl</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.ufcg.compiler.go.impl.VarDeclImpl
   * @see com.ufcg.compiler.go.impl.GoPackageImpl#getVarDecl()
   * @generated
   */
  int VAR_DECL = 2;

  /**
   * The feature id for the '<em><b>Tipo Decl</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VAR_DECL__TIPO_DECL = 0;

  /**
   * The feature id for the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VAR_DECL__ID = 1;

  /**
   * The feature id for the '<em><b>Atribuicao</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VAR_DECL__ATRIBUICAO = 2;

  /**
   * The feature id for the '<em><b>Expressao</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VAR_DECL__EXPRESSAO = 3;

  /**
   * The number of structural features of the '<em>Var Decl</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VAR_DECL_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link com.ufcg.compiler.go.impl.TIPOImpl <em>TIPO</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.ufcg.compiler.go.impl.TIPOImpl
   * @see com.ufcg.compiler.go.impl.GoPackageImpl#getTIPO()
   * @generated
   */
  int TIPO = 3;

  /**
   * The feature id for the '<em><b>Variavel</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TIPO__VARIAVEL = 0;

  /**
   * The feature id for the '<em><b>Constante</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TIPO__CONSTANTE = 1;

  /**
   * The number of structural features of the '<em>TIPO</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TIPO_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link com.ufcg.compiler.go.impl.IGUALImpl <em>IGUAL</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.ufcg.compiler.go.impl.IGUALImpl
   * @see com.ufcg.compiler.go.impl.GoPackageImpl#getIGUAL()
   * @generated
   */
  int IGUAL = 4;

  /**
   * The feature id for the '<em><b>Igual</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IGUAL__IGUAL = 0;

  /**
   * The number of structural features of the '<em>IGUAL</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IGUAL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link com.ufcg.compiler.go.impl.EXPRESSAOImpl <em>EXPRESSAO</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.ufcg.compiler.go.impl.EXPRESSAOImpl
   * @see com.ufcg.compiler.go.impl.GoPackageImpl#getEXPRESSAO()
   * @generated
   */
  int EXPRESSAO = 5;

  /**
   * The feature id for the '<em><b>Basic</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSAO__BASIC = 0;

  /**
   * The feature id for the '<em><b>Decl Function</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSAO__DECL_FUNCTION = 1;

  /**
   * The number of structural features of the '<em>EXPRESSAO</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSAO_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link com.ufcg.compiler.go.impl.LITERAIS_BASICOSImpl <em>LITERAIS BASICOS</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.ufcg.compiler.go.impl.LITERAIS_BASICOSImpl
   * @see com.ufcg.compiler.go.impl.GoPackageImpl#getLITERAIS_BASICOS()
   * @generated
   */
  int LITERAIS_BASICOS = 6;

  /**
   * The feature id for the '<em><b>Numero</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LITERAIS_BASICOS__NUMERO = 0;

  /**
   * The feature id for the '<em><b>String</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LITERAIS_BASICOS__STRING = 1;

  /**
   * The number of structural features of the '<em>LITERAIS BASICOS</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LITERAIS_BASICOS_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link com.ufcg.compiler.go.impl.FUNCAOImpl <em>FUNCAO</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.ufcg.compiler.go.impl.FUNCAOImpl
   * @see com.ufcg.compiler.go.impl.GoPackageImpl#getFUNCAO()
   * @generated
   */
  int FUNCAO = 7;

  /**
   * The feature id for the '<em><b>Func</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCAO__FUNC = 0;

  /**
   * The feature id for the '<em><b>Nome</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCAO__NOME = 1;

  /**
   * The feature id for the '<em><b>ABRE PARENTESES</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCAO__ABRE_PARENTESES = 2;

  /**
   * The feature id for the '<em><b>PARAMETERS LIST</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCAO__PARAMETERS_LIST = 3;

  /**
   * The feature id for the '<em><b>FECHA PARENTESES</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCAO__FECHA_PARENTESES = 4;

  /**
   * The feature id for the '<em><b>Bloco</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCAO__BLOCO = 5;

  /**
   * The number of structural features of the '<em>FUNCAO</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCAO_FEATURE_COUNT = 6;

  /**
   * The meta object id for the '{@link com.ufcg.compiler.go.impl.BLOCKImpl <em>BLOCK</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.ufcg.compiler.go.impl.BLOCKImpl
   * @see com.ufcg.compiler.go.impl.GoPackageImpl#getBLOCK()
   * @generated
   */
  int BLOCK = 8;

  /**
   * The feature id for the '<em><b>Lista De Comandos</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BLOCK__LISTA_DE_COMANDOS = 0;

  /**
   * The number of structural features of the '<em>BLOCK</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BLOCK_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link com.ufcg.compiler.go.impl.PARAMETERS_LISTImpl <em>PARAMETERS LIST</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.ufcg.compiler.go.impl.PARAMETERS_LISTImpl
   * @see com.ufcg.compiler.go.impl.GoPackageImpl#getPARAMETERS_LIST()
   * @generated
   */
  int PARAMETERS_LIST = 9;

  /**
   * The number of structural features of the '<em>PARAMETERS LIST</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETERS_LIST_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link com.ufcg.compiler.go.impl.PARAMETERImpl <em>PARAMETER</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.ufcg.compiler.go.impl.PARAMETERImpl
   * @see com.ufcg.compiler.go.impl.GoPackageImpl#getPARAMETER()
   * @generated
   */
  int PARAMETER = 10;

  /**
   * The feature id for the '<em><b>PARAMETER</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETER__PARAMETER = PARAMETERS_LIST_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETER__ID = PARAMETERS_LIST_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Tipo</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETER__TIPO = PARAMETERS_LIST_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>PARAMETER</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETER_FEATURE_COUNT = PARAMETERS_LIST_FEATURE_COUNT + 3;


  /**
   * Returns the meta object for class '{@link com.ufcg.compiler.go.Init <em>Init</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Init</em>'.
   * @see com.ufcg.compiler.go.Init
   * @generated
   */
  EClass getInit();

  /**
   * Returns the meta object for the containment reference list '{@link com.ufcg.compiler.go.Init#getElements <em>Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Elements</em>'.
   * @see com.ufcg.compiler.go.Init#getElements()
   * @see #getInit()
   * @generated
   */
  EReference getInit_Elements();

  /**
   * Returns the meta object for class '{@link com.ufcg.compiler.go.GoDecl <em>Decl</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Decl</em>'.
   * @see com.ufcg.compiler.go.GoDecl
   * @generated
   */
  EClass getGoDecl();

  /**
   * Returns the meta object for the containment reference '{@link com.ufcg.compiler.go.GoDecl#getVar <em>Var</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Var</em>'.
   * @see com.ufcg.compiler.go.GoDecl#getVar()
   * @see #getGoDecl()
   * @generated
   */
  EReference getGoDecl_Var();

  /**
   * Returns the meta object for the containment reference '{@link com.ufcg.compiler.go.GoDecl#getFunc <em>Func</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Func</em>'.
   * @see com.ufcg.compiler.go.GoDecl#getFunc()
   * @see #getGoDecl()
   * @generated
   */
  EReference getGoDecl_Func();

  /**
   * Returns the meta object for class '{@link com.ufcg.compiler.go.VarDecl <em>Var Decl</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Var Decl</em>'.
   * @see com.ufcg.compiler.go.VarDecl
   * @generated
   */
  EClass getVarDecl();

  /**
   * Returns the meta object for the containment reference '{@link com.ufcg.compiler.go.VarDecl#getTipoDecl <em>Tipo Decl</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Tipo Decl</em>'.
   * @see com.ufcg.compiler.go.VarDecl#getTipoDecl()
   * @see #getVarDecl()
   * @generated
   */
  EReference getVarDecl_TipoDecl();

  /**
   * Returns the meta object for the attribute '{@link com.ufcg.compiler.go.VarDecl#getId <em>Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Id</em>'.
   * @see com.ufcg.compiler.go.VarDecl#getId()
   * @see #getVarDecl()
   * @generated
   */
  EAttribute getVarDecl_Id();

  /**
   * Returns the meta object for the containment reference '{@link com.ufcg.compiler.go.VarDecl#getAtribuicao <em>Atribuicao</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Atribuicao</em>'.
   * @see com.ufcg.compiler.go.VarDecl#getAtribuicao()
   * @see #getVarDecl()
   * @generated
   */
  EReference getVarDecl_Atribuicao();

  /**
   * Returns the meta object for the containment reference '{@link com.ufcg.compiler.go.VarDecl#getExpressao <em>Expressao</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Expressao</em>'.
   * @see com.ufcg.compiler.go.VarDecl#getExpressao()
   * @see #getVarDecl()
   * @generated
   */
  EReference getVarDecl_Expressao();

  /**
   * Returns the meta object for class '{@link com.ufcg.compiler.go.TIPO <em>TIPO</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>TIPO</em>'.
   * @see com.ufcg.compiler.go.TIPO
   * @generated
   */
  EClass getTIPO();

  /**
   * Returns the meta object for the attribute '{@link com.ufcg.compiler.go.TIPO#getVariavel <em>Variavel</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Variavel</em>'.
   * @see com.ufcg.compiler.go.TIPO#getVariavel()
   * @see #getTIPO()
   * @generated
   */
  EAttribute getTIPO_Variavel();

  /**
   * Returns the meta object for the attribute '{@link com.ufcg.compiler.go.TIPO#getConstante <em>Constante</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Constante</em>'.
   * @see com.ufcg.compiler.go.TIPO#getConstante()
   * @see #getTIPO()
   * @generated
   */
  EAttribute getTIPO_Constante();

  /**
   * Returns the meta object for class '{@link com.ufcg.compiler.go.IGUAL <em>IGUAL</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>IGUAL</em>'.
   * @see com.ufcg.compiler.go.IGUAL
   * @generated
   */
  EClass getIGUAL();

  /**
   * Returns the meta object for the attribute '{@link com.ufcg.compiler.go.IGUAL#getIgual <em>Igual</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Igual</em>'.
   * @see com.ufcg.compiler.go.IGUAL#getIgual()
   * @see #getIGUAL()
   * @generated
   */
  EAttribute getIGUAL_Igual();

  /**
   * Returns the meta object for class '{@link com.ufcg.compiler.go.EXPRESSAO <em>EXPRESSAO</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>EXPRESSAO</em>'.
   * @see com.ufcg.compiler.go.EXPRESSAO
   * @generated
   */
  EClass getEXPRESSAO();

  /**
   * Returns the meta object for the containment reference '{@link com.ufcg.compiler.go.EXPRESSAO#getBasic <em>Basic</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Basic</em>'.
   * @see com.ufcg.compiler.go.EXPRESSAO#getBasic()
   * @see #getEXPRESSAO()
   * @generated
   */
  EReference getEXPRESSAO_Basic();

  /**
   * Returns the meta object for the containment reference '{@link com.ufcg.compiler.go.EXPRESSAO#getDeclFunction <em>Decl Function</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Decl Function</em>'.
   * @see com.ufcg.compiler.go.EXPRESSAO#getDeclFunction()
   * @see #getEXPRESSAO()
   * @generated
   */
  EReference getEXPRESSAO_DeclFunction();

  /**
   * Returns the meta object for class '{@link com.ufcg.compiler.go.LITERAIS_BASICOS <em>LITERAIS BASICOS</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>LITERAIS BASICOS</em>'.
   * @see com.ufcg.compiler.go.LITERAIS_BASICOS
   * @generated
   */
  EClass getLITERAIS_BASICOS();

  /**
   * Returns the meta object for the attribute '{@link com.ufcg.compiler.go.LITERAIS_BASICOS#getNumero <em>Numero</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Numero</em>'.
   * @see com.ufcg.compiler.go.LITERAIS_BASICOS#getNumero()
   * @see #getLITERAIS_BASICOS()
   * @generated
   */
  EAttribute getLITERAIS_BASICOS_Numero();

  /**
   * Returns the meta object for the attribute '{@link com.ufcg.compiler.go.LITERAIS_BASICOS#getString <em>String</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>String</em>'.
   * @see com.ufcg.compiler.go.LITERAIS_BASICOS#getString()
   * @see #getLITERAIS_BASICOS()
   * @generated
   */
  EAttribute getLITERAIS_BASICOS_String();

  /**
   * Returns the meta object for class '{@link com.ufcg.compiler.go.FUNCAO <em>FUNCAO</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>FUNCAO</em>'.
   * @see com.ufcg.compiler.go.FUNCAO
   * @generated
   */
  EClass getFUNCAO();

  /**
   * Returns the meta object for the attribute '{@link com.ufcg.compiler.go.FUNCAO#getFunc <em>Func</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Func</em>'.
   * @see com.ufcg.compiler.go.FUNCAO#getFunc()
   * @see #getFUNCAO()
   * @generated
   */
  EAttribute getFUNCAO_Func();

  /**
   * Returns the meta object for the attribute '{@link com.ufcg.compiler.go.FUNCAO#getNome <em>Nome</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Nome</em>'.
   * @see com.ufcg.compiler.go.FUNCAO#getNome()
   * @see #getFUNCAO()
   * @generated
   */
  EAttribute getFUNCAO_Nome();

  /**
   * Returns the meta object for the attribute '{@link com.ufcg.compiler.go.FUNCAO#getABRE_PARENTESES <em>ABRE PARENTESES</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>ABRE PARENTESES</em>'.
   * @see com.ufcg.compiler.go.FUNCAO#getABRE_PARENTESES()
   * @see #getFUNCAO()
   * @generated
   */
  EAttribute getFUNCAO_ABRE_PARENTESES();

  /**
   * Returns the meta object for the containment reference '{@link com.ufcg.compiler.go.FUNCAO#getPARAMETERS_LIST <em>PARAMETERS LIST</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>PARAMETERS LIST</em>'.
   * @see com.ufcg.compiler.go.FUNCAO#getPARAMETERS_LIST()
   * @see #getFUNCAO()
   * @generated
   */
  EReference getFUNCAO_PARAMETERS_LIST();

  /**
   * Returns the meta object for the attribute '{@link com.ufcg.compiler.go.FUNCAO#getFECHA_PARENTESES <em>FECHA PARENTESES</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>FECHA PARENTESES</em>'.
   * @see com.ufcg.compiler.go.FUNCAO#getFECHA_PARENTESES()
   * @see #getFUNCAO()
   * @generated
   */
  EAttribute getFUNCAO_FECHA_PARENTESES();

  /**
   * Returns the meta object for the containment reference '{@link com.ufcg.compiler.go.FUNCAO#getBloco <em>Bloco</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Bloco</em>'.
   * @see com.ufcg.compiler.go.FUNCAO#getBloco()
   * @see #getFUNCAO()
   * @generated
   */
  EReference getFUNCAO_Bloco();

  /**
   * Returns the meta object for class '{@link com.ufcg.compiler.go.BLOCK <em>BLOCK</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>BLOCK</em>'.
   * @see com.ufcg.compiler.go.BLOCK
   * @generated
   */
  EClass getBLOCK();

  /**
   * Returns the meta object for the containment reference list '{@link com.ufcg.compiler.go.BLOCK#getListaDeComandos <em>Lista De Comandos</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Lista De Comandos</em>'.
   * @see com.ufcg.compiler.go.BLOCK#getListaDeComandos()
   * @see #getBLOCK()
   * @generated
   */
  EReference getBLOCK_ListaDeComandos();

  /**
   * Returns the meta object for class '{@link com.ufcg.compiler.go.PARAMETERS_LIST <em>PARAMETERS LIST</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>PARAMETERS LIST</em>'.
   * @see com.ufcg.compiler.go.PARAMETERS_LIST
   * @generated
   */
  EClass getPARAMETERS_LIST();

  /**
   * Returns the meta object for class '{@link com.ufcg.compiler.go.PARAMETER <em>PARAMETER</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>PARAMETER</em>'.
   * @see com.ufcg.compiler.go.PARAMETER
   * @generated
   */
  EClass getPARAMETER();

  /**
   * Returns the meta object for the containment reference list '{@link com.ufcg.compiler.go.PARAMETER#getPARAMETER <em>PARAMETER</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>PARAMETER</em>'.
   * @see com.ufcg.compiler.go.PARAMETER#getPARAMETER()
   * @see #getPARAMETER()
   * @generated
   */
  EReference getPARAMETER_PARAMETER();

  /**
   * Returns the meta object for the attribute '{@link com.ufcg.compiler.go.PARAMETER#getId <em>Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Id</em>'.
   * @see com.ufcg.compiler.go.PARAMETER#getId()
   * @see #getPARAMETER()
   * @generated
   */
  EAttribute getPARAMETER_Id();

  /**
   * Returns the meta object for the attribute '{@link com.ufcg.compiler.go.PARAMETER#getTipo <em>Tipo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Tipo</em>'.
   * @see com.ufcg.compiler.go.PARAMETER#getTipo()
   * @see #getPARAMETER()
   * @generated
   */
  EAttribute getPARAMETER_Tipo();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  GoFactory getGoFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link com.ufcg.compiler.go.impl.InitImpl <em>Init</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.ufcg.compiler.go.impl.InitImpl
     * @see com.ufcg.compiler.go.impl.GoPackageImpl#getInit()
     * @generated
     */
    EClass INIT = eINSTANCE.getInit();

    /**
     * The meta object literal for the '<em><b>Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INIT__ELEMENTS = eINSTANCE.getInit_Elements();

    /**
     * The meta object literal for the '{@link com.ufcg.compiler.go.impl.GoDeclImpl <em>Decl</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.ufcg.compiler.go.impl.GoDeclImpl
     * @see com.ufcg.compiler.go.impl.GoPackageImpl#getGoDecl()
     * @generated
     */
    EClass GO_DECL = eINSTANCE.getGoDecl();

    /**
     * The meta object literal for the '<em><b>Var</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GO_DECL__VAR = eINSTANCE.getGoDecl_Var();

    /**
     * The meta object literal for the '<em><b>Func</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GO_DECL__FUNC = eINSTANCE.getGoDecl_Func();

    /**
     * The meta object literal for the '{@link com.ufcg.compiler.go.impl.VarDeclImpl <em>Var Decl</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.ufcg.compiler.go.impl.VarDeclImpl
     * @see com.ufcg.compiler.go.impl.GoPackageImpl#getVarDecl()
     * @generated
     */
    EClass VAR_DECL = eINSTANCE.getVarDecl();

    /**
     * The meta object literal for the '<em><b>Tipo Decl</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VAR_DECL__TIPO_DECL = eINSTANCE.getVarDecl_TipoDecl();

    /**
     * The meta object literal for the '<em><b>Id</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VAR_DECL__ID = eINSTANCE.getVarDecl_Id();

    /**
     * The meta object literal for the '<em><b>Atribuicao</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VAR_DECL__ATRIBUICAO = eINSTANCE.getVarDecl_Atribuicao();

    /**
     * The meta object literal for the '<em><b>Expressao</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VAR_DECL__EXPRESSAO = eINSTANCE.getVarDecl_Expressao();

    /**
     * The meta object literal for the '{@link com.ufcg.compiler.go.impl.TIPOImpl <em>TIPO</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.ufcg.compiler.go.impl.TIPOImpl
     * @see com.ufcg.compiler.go.impl.GoPackageImpl#getTIPO()
     * @generated
     */
    EClass TIPO = eINSTANCE.getTIPO();

    /**
     * The meta object literal for the '<em><b>Variavel</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TIPO__VARIAVEL = eINSTANCE.getTIPO_Variavel();

    /**
     * The meta object literal for the '<em><b>Constante</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TIPO__CONSTANTE = eINSTANCE.getTIPO_Constante();

    /**
     * The meta object literal for the '{@link com.ufcg.compiler.go.impl.IGUALImpl <em>IGUAL</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.ufcg.compiler.go.impl.IGUALImpl
     * @see com.ufcg.compiler.go.impl.GoPackageImpl#getIGUAL()
     * @generated
     */
    EClass IGUAL = eINSTANCE.getIGUAL();

    /**
     * The meta object literal for the '<em><b>Igual</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute IGUAL__IGUAL = eINSTANCE.getIGUAL_Igual();

    /**
     * The meta object literal for the '{@link com.ufcg.compiler.go.impl.EXPRESSAOImpl <em>EXPRESSAO</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.ufcg.compiler.go.impl.EXPRESSAOImpl
     * @see com.ufcg.compiler.go.impl.GoPackageImpl#getEXPRESSAO()
     * @generated
     */
    EClass EXPRESSAO = eINSTANCE.getEXPRESSAO();

    /**
     * The meta object literal for the '<em><b>Basic</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPRESSAO__BASIC = eINSTANCE.getEXPRESSAO_Basic();

    /**
     * The meta object literal for the '<em><b>Decl Function</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPRESSAO__DECL_FUNCTION = eINSTANCE.getEXPRESSAO_DeclFunction();

    /**
     * The meta object literal for the '{@link com.ufcg.compiler.go.impl.LITERAIS_BASICOSImpl <em>LITERAIS BASICOS</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.ufcg.compiler.go.impl.LITERAIS_BASICOSImpl
     * @see com.ufcg.compiler.go.impl.GoPackageImpl#getLITERAIS_BASICOS()
     * @generated
     */
    EClass LITERAIS_BASICOS = eINSTANCE.getLITERAIS_BASICOS();

    /**
     * The meta object literal for the '<em><b>Numero</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LITERAIS_BASICOS__NUMERO = eINSTANCE.getLITERAIS_BASICOS_Numero();

    /**
     * The meta object literal for the '<em><b>String</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LITERAIS_BASICOS__STRING = eINSTANCE.getLITERAIS_BASICOS_String();

    /**
     * The meta object literal for the '{@link com.ufcg.compiler.go.impl.FUNCAOImpl <em>FUNCAO</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.ufcg.compiler.go.impl.FUNCAOImpl
     * @see com.ufcg.compiler.go.impl.GoPackageImpl#getFUNCAO()
     * @generated
     */
    EClass FUNCAO = eINSTANCE.getFUNCAO();

    /**
     * The meta object literal for the '<em><b>Func</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FUNCAO__FUNC = eINSTANCE.getFUNCAO_Func();

    /**
     * The meta object literal for the '<em><b>Nome</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FUNCAO__NOME = eINSTANCE.getFUNCAO_Nome();

    /**
     * The meta object literal for the '<em><b>ABRE PARENTESES</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FUNCAO__ABRE_PARENTESES = eINSTANCE.getFUNCAO_ABRE_PARENTESES();

    /**
     * The meta object literal for the '<em><b>PARAMETERS LIST</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FUNCAO__PARAMETERS_LIST = eINSTANCE.getFUNCAO_PARAMETERS_LIST();

    /**
     * The meta object literal for the '<em><b>FECHA PARENTESES</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FUNCAO__FECHA_PARENTESES = eINSTANCE.getFUNCAO_FECHA_PARENTESES();

    /**
     * The meta object literal for the '<em><b>Bloco</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FUNCAO__BLOCO = eINSTANCE.getFUNCAO_Bloco();

    /**
     * The meta object literal for the '{@link com.ufcg.compiler.go.impl.BLOCKImpl <em>BLOCK</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.ufcg.compiler.go.impl.BLOCKImpl
     * @see com.ufcg.compiler.go.impl.GoPackageImpl#getBLOCK()
     * @generated
     */
    EClass BLOCK = eINSTANCE.getBLOCK();

    /**
     * The meta object literal for the '<em><b>Lista De Comandos</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BLOCK__LISTA_DE_COMANDOS = eINSTANCE.getBLOCK_ListaDeComandos();

    /**
     * The meta object literal for the '{@link com.ufcg.compiler.go.impl.PARAMETERS_LISTImpl <em>PARAMETERS LIST</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.ufcg.compiler.go.impl.PARAMETERS_LISTImpl
     * @see com.ufcg.compiler.go.impl.GoPackageImpl#getPARAMETERS_LIST()
     * @generated
     */
    EClass PARAMETERS_LIST = eINSTANCE.getPARAMETERS_LIST();

    /**
     * The meta object literal for the '{@link com.ufcg.compiler.go.impl.PARAMETERImpl <em>PARAMETER</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.ufcg.compiler.go.impl.PARAMETERImpl
     * @see com.ufcg.compiler.go.impl.GoPackageImpl#getPARAMETER()
     * @generated
     */
    EClass PARAMETER = eINSTANCE.getPARAMETER();

    /**
     * The meta object literal for the '<em><b>PARAMETER</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PARAMETER__PARAMETER = eINSTANCE.getPARAMETER_PARAMETER();

    /**
     * The meta object literal for the '<em><b>Id</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARAMETER__ID = eINSTANCE.getPARAMETER_Id();

    /**
     * The meta object literal for the '<em><b>Tipo</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARAMETER__TIPO = eINSTANCE.getPARAMETER_Tipo();

  }

} //GoPackage
