/**
 * generated by Xtext 2.14.0
 */
package com.ufcg.compiler.go;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>ID List</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.ufcg.compiler.go.IDList#getIdList <em>Id List</em>}</li>
 *   <li>{@link com.ufcg.compiler.go.IDList#getList <em>List</em>}</li>
 * </ul>
 *
 * @see com.ufcg.compiler.go.GoPackage#getIDList()
 * @model
 * @generated
 */
public interface IDList extends EObject
{
  /**
   * Returns the value of the '<em><b>Id List</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Id List</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Id List</em>' attribute list.
   * @see com.ufcg.compiler.go.GoPackage#getIDList_IdList()
   * @model unique="false"
   * @generated
   */
  EList<String> getIdList();

  /**
   * Returns the value of the '<em><b>List</b></em>' containment reference list.
   * The list contents are of type {@link com.ufcg.compiler.go.IDList}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>List</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>List</em>' containment reference list.
   * @see com.ufcg.compiler.go.GoPackage#getIDList_List()
   * @model containment="true"
   * @generated
   */
  EList<IDList> getList();

} // IDList
