/**
 * generated by Xtext 2.14.0
 */
package com.ufcg.compiler.go;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>LITERAIS BASICOS</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.ufcg.compiler.go.LITERAIS_BASICOS#getNumero <em>Numero</em>}</li>
 *   <li>{@link com.ufcg.compiler.go.LITERAIS_BASICOS#getString <em>String</em>}</li>
 * </ul>
 *
 * @see com.ufcg.compiler.go.GoPackage#getLITERAIS_BASICOS()
 * @model
 * @generated
 */
public interface LITERAIS_BASICOS extends EObject
{
  /**
   * Returns the value of the '<em><b>Numero</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Numero</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Numero</em>' attribute.
   * @see #setNumero(String)
   * @see com.ufcg.compiler.go.GoPackage#getLITERAIS_BASICOS_Numero()
   * @model
   * @generated
   */
  String getNumero();

  /**
   * Sets the value of the '{@link com.ufcg.compiler.go.LITERAIS_BASICOS#getNumero <em>Numero</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Numero</em>' attribute.
   * @see #getNumero()
   * @generated
   */
  void setNumero(String value);

  /**
   * Returns the value of the '<em><b>String</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>String</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>String</em>' attribute.
   * @see #setString(String)
   * @see com.ufcg.compiler.go.GoPackage#getLITERAIS_BASICOS_String()
   * @model
   * @generated
   */
  String getString();

  /**
   * Sets the value of the '{@link com.ufcg.compiler.go.LITERAIS_BASICOS#getString <em>String</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>String</em>' attribute.
   * @see #getString()
   * @generated
   */
  void setString(String value);

} // LITERAIS_BASICOS
