/**
 * generated by Xtext 2.14.0
 */
package com.ufcg.compiler.go;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Parameters</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.ufcg.compiler.go.Parameters#getRetorno <em>Retorno</em>}</li>
 * </ul>
 *
 * @see com.ufcg.compiler.go.GoPackage#getParameters()
 * @model
 * @generated
 */
public interface Parameters extends Signature
{
  /**
   * Returns the value of the '<em><b>Retorno</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Retorno</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Retorno</em>' containment reference.
   * @see #setRetorno(Result)
   * @see com.ufcg.compiler.go.GoPackage#getParameters_Retorno()
   * @model containment="true"
   * @generated
   */
  Result getRetorno();

  /**
   * Sets the value of the '{@link com.ufcg.compiler.go.Parameters#getRetorno <em>Retorno</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Retorno</em>' containment reference.
   * @see #getRetorno()
   * @generated
   */
  void setRetorno(Result value);

} // Parameters
