/*
 * generated by Xtext 2.14.0
 */
package com.ufcg.compiler.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractGoScopeProvider extends DelegatingScopeProvider {
}
