/**
 * generated by Xtext 2.14.0
 */
package com.ufcg.compiler;

import com.ufcg.compiler.GoStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class GoStandaloneSetup extends GoStandaloneSetupGenerated {
  public static void doSetup() {
    new GoStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
