/**
 * generated by Xtext 2.14.0
 */
package com.ufcg.compiler.go;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Post Stmt</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.ufcg.compiler.go.PostStmt#getDecl <em>Decl</em>}</li>
 * </ul>
 *
 * @see com.ufcg.compiler.go.GoPackage#getPostStmt()
 * @model
 * @generated
 */
public interface PostStmt extends EObject
{
  /**
   * Returns the value of the '<em><b>Decl</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Decl</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Decl</em>' containment reference.
   * @see #setDecl(GoDecl)
   * @see com.ufcg.compiler.go.GoPackage#getPostStmt_Decl()
   * @model containment="true"
   * @generated
   */
  GoDecl getDecl();

  /**
   * Sets the value of the '{@link com.ufcg.compiler.go.PostStmt#getDecl <em>Decl</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Decl</em>' containment reference.
   * @see #getDecl()
   * @generated
   */
  void setDecl(GoDecl value);

} // PostStmt
