/**
 * generated by Xtext 2.14.0
 */
package com.ufcg.compiler.go.impl;

import com.ufcg.compiler.go.GoPackage;
import com.ufcg.compiler.go.PARAMETERS_LIST;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>PARAMETERS LIST</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class PARAMETERS_LISTImpl extends MinimalEObjectImpl.Container implements PARAMETERS_LIST
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected PARAMETERS_LISTImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GoPackage.Literals.PARAMETERS_LIST;
  }

} //PARAMETERS_LISTImpl
