/**
 * generated by Xtext 2.14.0
 */
package com.ufcg.compiler.go.impl;

import com.ufcg.compiler.go.GoPackage;
import com.ufcg.compiler.go.TIPO;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>TIPO</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link com.ufcg.compiler.go.impl.TIPOImpl#getVariavel <em>Variavel</em>}</li>
 *   <li>{@link com.ufcg.compiler.go.impl.TIPOImpl#getConstante <em>Constante</em>}</li>
 * </ul>
 *
 * @generated
 */
public class TIPOImpl extends MinimalEObjectImpl.Container implements TIPO
{
  /**
   * The default value of the '{@link #getVariavel() <em>Variavel</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVariavel()
   * @generated
   * @ordered
   */
  protected static final String VARIAVEL_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getVariavel() <em>Variavel</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVariavel()
   * @generated
   * @ordered
   */
  protected String variavel = VARIAVEL_EDEFAULT;

  /**
   * The default value of the '{@link #getConstante() <em>Constante</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getConstante()
   * @generated
   * @ordered
   */
  protected static final String CONSTANTE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getConstante() <em>Constante</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getConstante()
   * @generated
   * @ordered
   */
  protected String constante = CONSTANTE_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected TIPOImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GoPackage.Literals.TIPO;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getVariavel()
  {
    return variavel;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setVariavel(String newVariavel)
  {
    String oldVariavel = variavel;
    variavel = newVariavel;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GoPackage.TIPO__VARIAVEL, oldVariavel, variavel));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getConstante()
  {
    return constante;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setConstante(String newConstante)
  {
    String oldConstante = constante;
    constante = newConstante;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GoPackage.TIPO__CONSTANTE, oldConstante, constante));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case GoPackage.TIPO__VARIAVEL:
        return getVariavel();
      case GoPackage.TIPO__CONSTANTE:
        return getConstante();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case GoPackage.TIPO__VARIAVEL:
        setVariavel((String)newValue);
        return;
      case GoPackage.TIPO__CONSTANTE:
        setConstante((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case GoPackage.TIPO__VARIAVEL:
        setVariavel(VARIAVEL_EDEFAULT);
        return;
      case GoPackage.TIPO__CONSTANTE:
        setConstante(CONSTANTE_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case GoPackage.TIPO__VARIAVEL:
        return VARIAVEL_EDEFAULT == null ? variavel != null : !VARIAVEL_EDEFAULT.equals(variavel);
      case GoPackage.TIPO__CONSTANTE:
        return CONSTANTE_EDEFAULT == null ? constante != null : !CONSTANTE_EDEFAULT.equals(constante);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (variavel: ");
    result.append(variavel);
    result.append(", constante: ");
    result.append(constante);
    result.append(')');
    return result.toString();
  }

} //TIPOImpl
