/**
 * generated by Xtext 2.14.0
 */
package com.ufcg.compiladores.go;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>ARIT EXPR</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.ufcg.compiladores.go.ARIT_EXPR#getNum1 <em>Num1</em>}</li>
 *   <li>{@link com.ufcg.compiladores.go.ARIT_EXPR#getVar1 <em>Var1</em>}</li>
 *   <li>{@link com.ufcg.compiladores.go.ARIT_EXPR#getOp <em>Op</em>}</li>
 *   <li>{@link com.ufcg.compiladores.go.ARIT_EXPR#getNum2 <em>Num2</em>}</li>
 *   <li>{@link com.ufcg.compiladores.go.ARIT_EXPR#getVar2 <em>Var2</em>}</li>
 *   <li>{@link com.ufcg.compiladores.go.ARIT_EXPR#getNum <em>Num</em>}</li>
 *   <li>{@link com.ufcg.compiladores.go.ARIT_EXPR#getVar <em>Var</em>}</li>
 *   <li>{@link com.ufcg.compiladores.go.ARIT_EXPR#getAtr <em>Atr</em>}</li>
 * </ul>
 *
 * @see com.ufcg.compiladores.go.GoPackage#getARIT_EXPR()
 * @model
 * @generated
 */
public interface ARIT_EXPR extends EObject
{
  /**
   * Returns the value of the '<em><b>Num1</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Num1</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Num1</em>' attribute.
   * @see #setNum1(String)
   * @see com.ufcg.compiladores.go.GoPackage#getARIT_EXPR_Num1()
   * @model
   * @generated
   */
  String getNum1();

  /**
   * Sets the value of the '{@link com.ufcg.compiladores.go.ARIT_EXPR#getNum1 <em>Num1</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Num1</em>' attribute.
   * @see #getNum1()
   * @generated
   */
  void setNum1(String value);

  /**
   * Returns the value of the '<em><b>Var1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Var1</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Var1</em>' containment reference.
   * @see #setVar1(VarCall)
   * @see com.ufcg.compiladores.go.GoPackage#getARIT_EXPR_Var1()
   * @model containment="true"
   * @generated
   */
  VarCall getVar1();

  /**
   * Sets the value of the '{@link com.ufcg.compiladores.go.ARIT_EXPR#getVar1 <em>Var1</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Var1</em>' containment reference.
   * @see #getVar1()
   * @generated
   */
  void setVar1(VarCall value);

  /**
   * Returns the value of the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Op</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Op</em>' attribute.
   * @see #setOp(String)
   * @see com.ufcg.compiladores.go.GoPackage#getARIT_EXPR_Op()
   * @model
   * @generated
   */
  String getOp();

  /**
   * Sets the value of the '{@link com.ufcg.compiladores.go.ARIT_EXPR#getOp <em>Op</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Op</em>' attribute.
   * @see #getOp()
   * @generated
   */
  void setOp(String value);

  /**
   * Returns the value of the '<em><b>Num2</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Num2</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Num2</em>' attribute.
   * @see #setNum2(String)
   * @see com.ufcg.compiladores.go.GoPackage#getARIT_EXPR_Num2()
   * @model
   * @generated
   */
  String getNum2();

  /**
   * Sets the value of the '{@link com.ufcg.compiladores.go.ARIT_EXPR#getNum2 <em>Num2</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Num2</em>' attribute.
   * @see #getNum2()
   * @generated
   */
  void setNum2(String value);

  /**
   * Returns the value of the '<em><b>Var2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Var2</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Var2</em>' containment reference.
   * @see #setVar2(VarCall)
   * @see com.ufcg.compiladores.go.GoPackage#getARIT_EXPR_Var2()
   * @model containment="true"
   * @generated
   */
  VarCall getVar2();

  /**
   * Sets the value of the '{@link com.ufcg.compiladores.go.ARIT_EXPR#getVar2 <em>Var2</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Var2</em>' containment reference.
   * @see #getVar2()
   * @generated
   */
  void setVar2(VarCall value);

  /**
   * Returns the value of the '<em><b>Num</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Num</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Num</em>' attribute.
   * @see #setNum(String)
   * @see com.ufcg.compiladores.go.GoPackage#getARIT_EXPR_Num()
   * @model
   * @generated
   */
  String getNum();

  /**
   * Sets the value of the '{@link com.ufcg.compiladores.go.ARIT_EXPR#getNum <em>Num</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Num</em>' attribute.
   * @see #getNum()
   * @generated
   */
  void setNum(String value);

  /**
   * Returns the value of the '<em><b>Var</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Var</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Var</em>' containment reference.
   * @see #setVar(VarCall)
   * @see com.ufcg.compiladores.go.GoPackage#getARIT_EXPR_Var()
   * @model containment="true"
   * @generated
   */
  VarCall getVar();

  /**
   * Sets the value of the '{@link com.ufcg.compiladores.go.ARIT_EXPR#getVar <em>Var</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Var</em>' containment reference.
   * @see #getVar()
   * @generated
   */
  void setVar(VarCall value);

  /**
   * Returns the value of the '<em><b>Atr</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Atr</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Atr</em>' attribute.
   * @see #setAtr(String)
   * @see com.ufcg.compiladores.go.GoPackage#getARIT_EXPR_Atr()
   * @model
   * @generated
   */
  String getAtr();

  /**
   * Sets the value of the '{@link com.ufcg.compiladores.go.ARIT_EXPR#getAtr <em>Atr</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Atr</em>' attribute.
   * @see #getAtr()
   * @generated
   */
  void setAtr(String value);

} // ARIT_EXPR
