/**
 * generated by Xtext 2.14.0
 */
package com.ufcg.compiladores.go;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>IGUAL</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.ufcg.compiladores.go.IGUAL#getIgual <em>Igual</em>}</li>
 * </ul>
 *
 * @see com.ufcg.compiladores.go.GoPackage#getIGUAL()
 * @model
 * @generated
 */
public interface IGUAL extends EObject
{
  /**
   * Returns the value of the '<em><b>Igual</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Igual</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Igual</em>' attribute.
   * @see #setIgual(String)
   * @see com.ufcg.compiladores.go.GoPackage#getIGUAL_Igual()
   * @model
   * @generated
   */
  String getIgual();

  /**
   * Sets the value of the '{@link com.ufcg.compiladores.go.IGUAL#getIgual <em>Igual</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Igual</em>' attribute.
   * @see #getIgual()
   * @generated
   */
  void setIgual(String value);

} // IGUAL
