/**
 * generated by Xtext 2.14.0
 */
package com.ufcg.compiladores.go;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Return Stmt</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.ufcg.compiladores.go.ReturnStmt#getBasic <em>Basic</em>}</li>
 *   <li>{@link com.ufcg.compiladores.go.ReturnStmt#getFunc <em>Func</em>}</li>
 *   <li>{@link com.ufcg.compiladores.go.ReturnStmt#getIdVar <em>Id Var</em>}</li>
 * </ul>
 *
 * @see com.ufcg.compiladores.go.GoPackage#getReturnStmt()
 * @model
 * @generated
 */
public interface ReturnStmt extends EObject
{
  /**
   * Returns the value of the '<em><b>Basic</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Basic</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Basic</em>' containment reference.
   * @see #setBasic(LITERAIS_BASICOS)
   * @see com.ufcg.compiladores.go.GoPackage#getReturnStmt_Basic()
   * @model containment="true"
   * @generated
   */
  LITERAIS_BASICOS getBasic();

  /**
   * Sets the value of the '{@link com.ufcg.compiladores.go.ReturnStmt#getBasic <em>Basic</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Basic</em>' containment reference.
   * @see #getBasic()
   * @generated
   */
  void setBasic(LITERAIS_BASICOS value);

  /**
   * Returns the value of the '<em><b>Func</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Func</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Func</em>' containment reference.
   * @see #setFunc(FunctionCall)
   * @see com.ufcg.compiladores.go.GoPackage#getReturnStmt_Func()
   * @model containment="true"
   * @generated
   */
  FunctionCall getFunc();

  /**
   * Sets the value of the '{@link com.ufcg.compiladores.go.ReturnStmt#getFunc <em>Func</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Func</em>' containment reference.
   * @see #getFunc()
   * @generated
   */
  void setFunc(FunctionCall value);

  /**
   * Returns the value of the '<em><b>Id Var</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Id Var</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Id Var</em>' containment reference.
   * @see #setIdVar(VarCall)
   * @see com.ufcg.compiladores.go.GoPackage#getReturnStmt_IdVar()
   * @model containment="true"
   * @generated
   */
  VarCall getIdVar();

  /**
   * Sets the value of the '{@link com.ufcg.compiladores.go.ReturnStmt#getIdVar <em>Id Var</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Id Var</em>' containment reference.
   * @see #getIdVar()
   * @generated
   */
  void setIdVar(VarCall value);

} // ReturnStmt
