/**
 * generated by Xtext 2.14.0
 */
package com.ufcg.compiler.ide;

import com.ufcg.compiler.ide.AbstractGoIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class GoIdeModule extends AbstractGoIdeModule {
}
