/*
 * generated by Xtext 2.14.0
 */
package com.ufcg.compiladores.parser.antlr;

import com.google.inject.Inject;
import com.ufcg.compiladores.parser.antlr.internal.InternalGoParser;
import com.ufcg.compiladores.services.GoGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class GoParser extends AbstractAntlrParser {

	@Inject
	private GoGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalGoParser createParser(XtextTokenStream stream) {
		return new InternalGoParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Init";
	}

	public GoGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(GoGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
